import {
  boolean,
  date,
  index,
  integer,
  numeric,
  pgTable,
  serial,
  text,
  timestamp,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { projectsTable } from "./projects";
import { environmentsTable, tenantsTable, usersTable } from "./tenants";

export const tradePartnersTable = pgTable("trade_partners", {
  id: serial("id").primaryKey(),
  companyName: text("company_name").notNull(),
  normalizedName: text("normalized_name").notNull(),
  tradeCapabilities: text("trade_capabilities").array().notNull().default([]),
  serviceAreas: text("service_areas").array().notNull().default([]),
  primaryContact: text("primary_contact"),
  email: text("email"),
  phone: text("phone"),
  qualificationStatus: text("qualification_status").notNull().default("pending"),
  qualificationReviewedAt: timestamp("qualification_reviewed_at", { withTimezone: true }),
  qualificationReviewedByUserId: integer("qualification_reviewed_by_user_id").references(() => usersTable.id, { onDelete: "set null" }),
  qualificationNotes: text("qualification_notes"),
  status: text("status").notNull().default("active"),
  tenantId: integer("tenant_id").notNull().references(() => tenantsTable.id, { onDelete: "cascade" }),
  environmentId: integer("environment_id").notNull().references(() => environmentsTable.id, { onDelete: "cascade" }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  uniqueIndex("trade_partners_scope_name_idx").on(table.tenantId, table.environmentId, table.normalizedName),
  index("trade_partners_scope_status_idx").on(table.tenantId, table.environmentId, table.status),
]);

export const tradePartnerComplianceDocumentsTable = pgTable("trade_partner_compliance_documents", {
  id: serial("id").primaryKey(),
  tradePartnerId: integer("trade_partner_id").notNull().references(() => tradePartnersTable.id, { onDelete: "cascade" }),
  projectId: integer("project_id").references(() => projectsTable.id, { onDelete: "cascade" }),
  documentType: text("document_type").notNull(),
  title: text("title").notNull(),
  documentNumber: text("document_number"),
  issuer: text("issuer"),
  expiresOn: date("expires_on", { mode: "string" }),
  status: text("status").notNull().default("requested"),
  objectPath: text("object_path"),
  originalName: text("original_name"),
  contentType: text("content_type"),
  fileSize: integer("file_size"),
  malwareScanStatus: text("malware_scan_status").notNull().default("not_scanned"),
  malwareScannedAt: timestamp("malware_scanned_at", { withTimezone: true }),
  pendingObjectPath: text("pending_object_path"),
  pendingOriginalName: text("pending_original_name"),
  pendingContentType: text("pending_content_type"),
  pendingFileSize: integer("pending_file_size"),
  pendingMalwareScanStatus: text("pending_malware_scan_status").notNull().default("not_scanned"),
  pendingMalwareScannedAt: timestamp("pending_malware_scanned_at", { withTimezone: true }),
  uploadedByUserId: integer("uploaded_by_user_id").references(() => usersTable.id, { onDelete: "set null" }),
  reviewedByUserId: integer("reviewed_by_user_id").references(() => usersTable.id, { onDelete: "set null" }),
  reviewedAt: timestamp("reviewed_at", { withTimezone: true }),
  reviewNotes: text("review_notes"),
  tenantId: integer("tenant_id").notNull().references(() => tenantsTable.id, { onDelete: "cascade" }),
  environmentId: integer("environment_id").notNull().references(() => environmentsTable.id, { onDelete: "cascade" }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index("trade_partner_compliance_scope_partner_idx").on(table.tenantId, table.environmentId, table.tradePartnerId),
  index("trade_partner_compliance_expiry_idx").on(table.tenantId, table.environmentId, table.expiresOn, table.status),
]);

export const projectComplianceRequirementsTable = pgTable("project_compliance_requirements", {
  id: serial("id").primaryKey(),
  projectId: integer("project_id").notNull().references(() => projectsTable.id, { onDelete: "cascade" }),
  tradePartnerId: integer("trade_partner_id").notNull().references(() => tradePartnersTable.id, { onDelete: "cascade" }),
  requirementType: text("requirement_type").notNull(),
  title: text("title").notNull(),
  status: text("status").notNull().default("open"),
  dueDate: date("due_date", { mode: "string" }),
  blocksAward: boolean("blocks_award").notNull().default(false),
  blocksMobilization: boolean("blocks_mobilization").notNull().default(false),
  blocksBilling: boolean("blocks_billing").notNull().default(false),
  blocksCloseout: boolean("blocks_closeout").notNull().default(false),
  complianceDocumentId: integer("compliance_document_id").references(() => tradePartnerComplianceDocumentsTable.id, { onDelete: "set null" }),
  notes: text("notes"),
  tenantId: integer("tenant_id").notNull().references(() => tenantsTable.id, { onDelete: "cascade" }),
  environmentId: integer("environment_id").notNull().references(() => environmentsTable.id, { onDelete: "cascade" }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index("project_compliance_requirements_scope_project_idx").on(table.tenantId, table.environmentId, table.projectId),
  index("project_compliance_requirements_scope_partner_idx").on(table.tenantId, table.environmentId, table.tradePartnerId),
]);

export const subcontractAgreementsTable = pgTable("subcontract_agreements", {
  id: serial("id").primaryKey(),
  projectId: integer("project_id").notNull().references(() => projectsTable.id, { onDelete: "cascade" }),
  tradePartnerId: integer("trade_partner_id").notNull().references(() => tradePartnersTable.id, { onDelete: "restrict" }),
  agreementNumber: text("agreement_number").notNull(),
  scope: text("scope").notNull(),
  originalValue: numeric("original_value", { precision: 14, scale: 2 }).notNull().default("0"),
  currentValue: numeric("current_value", { precision: 14, scale: 2 }).notNull().default("0"),
  contractStart: date("contract_start", { mode: "string" }),
  contractEnd: date("contract_end", { mode: "string" }),
  paymentTerms: text("payment_terms"),
  retainagePercent: numeric("retainage_percent", { precision: 5, scale: 2 }).notNull().default("10"),
  approvalStatus: text("approval_status").notNull().default("draft"),
  status: text("status").notNull().default("active"),
  approvedByUserId: integer("approved_by_user_id").references(() => usersTable.id, { onDelete: "set null" }),
  approvedAt: timestamp("approved_at", { withTimezone: true }),
  tenantId: integer("tenant_id").notNull().references(() => tenantsTable.id, { onDelete: "cascade" }),
  environmentId: integer("environment_id").notNull().references(() => environmentsTable.id, { onDelete: "cascade" }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  uniqueIndex("subcontract_agreements_scope_number_idx").on(table.tenantId, table.environmentId, table.projectId, table.agreementNumber),
  index("subcontract_agreements_scope_partner_idx").on(table.tenantId, table.environmentId, table.tradePartnerId),
]);

export const subcontractScheduleOfValuesTable = pgTable("subcontract_schedule_of_values", {
  id: serial("id").primaryKey(),
  agreementId: integer("agreement_id").notNull().references(() => subcontractAgreementsTable.id, { onDelete: "cascade" }),
  lineNumber: text("line_number").notNull(),
  description: text("description").notNull(),
  scheduledValue: numeric("scheduled_value", { precision: 14, scale: 2 }).notNull().default("0"),
  approvedValue: numeric("approved_value", { precision: 14, scale: 2 }).notNull().default("0"),
  billedToDate: numeric("billed_to_date", { precision: 14, scale: 2 }).notNull().default("0"),
  percentComplete: numeric("percent_complete", { precision: 5, scale: 2 }).notNull().default("0"),
  retentionHeld: numeric("retention_held", { precision: 14, scale: 2 }).notNull().default("0"),
  status: text("status").notNull().default("draft"),
  tenantId: integer("tenant_id").notNull().references(() => tenantsTable.id, { onDelete: "cascade" }),
  environmentId: integer("environment_id").notNull().references(() => environmentsTable.id, { onDelete: "cascade" }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  uniqueIndex("subcontract_sov_scope_line_idx").on(table.tenantId, table.environmentId, table.agreementId, table.lineNumber),
  index("subcontract_sov_scope_agreement_idx").on(table.tenantId, table.environmentId, table.agreementId),
]);

export const subcontractChangeOrdersTable = pgTable("subcontract_change_orders", {
  id: serial("id").primaryKey(),
  agreementId: integer("agreement_id").notNull().references(() => subcontractAgreementsTable.id, { onDelete: "cascade" }),
  changeNumber: text("change_number").notNull(),
  title: text("title").notNull(),
  description: text("description"),
  proposedValue: numeric("proposed_value", { precision: 14, scale: 2 }).notNull().default("0"),
  approvedValue: numeric("approved_value", { precision: 14, scale: 2 }).notNull().default("0"),
  approvalStatus: text("approval_status").notNull().default("pending"),
  scheduleImpactDays: integer("schedule_impact_days").notNull().default(0),
  requestedBy: text("requested_by"),
  approvedByUserId: integer("approved_by_user_id").references(() => usersTable.id, { onDelete: "set null" }),
  approvedAt: timestamp("approved_at", { withTimezone: true }),
  rejectionReason: text("rejection_reason"),
  tenantId: integer("tenant_id").notNull().references(() => tenantsTable.id, { onDelete: "cascade" }),
  environmentId: integer("environment_id").notNull().references(() => environmentsTable.id, { onDelete: "cascade" }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  uniqueIndex("subcontract_change_orders_scope_number_idx").on(table.tenantId, table.environmentId, table.agreementId, table.changeNumber),
  index("subcontract_change_orders_scope_agreement_idx").on(table.tenantId, table.environmentId, table.agreementId),
]);

export const subcontractPayApplicationsTable = pgTable("subcontract_pay_applications", {
  id: serial("id").primaryKey(),
  agreementId: integer("agreement_id").notNull().references(() => subcontractAgreementsTable.id, { onDelete: "cascade" }),
  applicationNumber: text("application_number").notNull(),
  periodStart: date("period_start", { mode: "string" }),
  periodEnd: date("period_end", { mode: "string" }),
  grossAmount: numeric("gross_amount", { precision: 14, scale: 2 }).notNull().default("0"),
  retainageAmount: numeric("retainage_amount", { precision: 14, scale: 2 }).notNull().default("0"),
  netAmount: numeric("net_amount", { precision: 14, scale: 2 }).notNull().default("0"),
  storedMaterialsAmount: numeric("stored_materials_amount", { precision: 14, scale: 2 }).notNull().default("0"),
  status: text("status").notNull().default("draft"),
  waiverStatus: text("waiver_status").notNull().default("missing"),
  submittedByUserId: integer("submitted_by_user_id").references(() => usersTable.id, { onDelete: "set null" }),
  submittedAt: timestamp("submitted_at", { withTimezone: true }),
  approvedByUserId: integer("approved_by_user_id").references(() => usersTable.id, { onDelete: "set null" }),
  approvedAt: timestamp("approved_at", { withTimezone: true }),
  rejectionReason: text("rejection_reason"),
  supportingDocumentPaths: text("supporting_document_paths").array().notNull().default([]),
  tenantId: integer("tenant_id").notNull().references(() => tenantsTable.id, { onDelete: "cascade" }),
  environmentId: integer("environment_id").notNull().references(() => environmentsTable.id, { onDelete: "cascade" }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  uniqueIndex("subcontract_pay_applications_scope_number_idx").on(table.tenantId, table.environmentId, table.agreementId, table.applicationNumber),
  index("subcontract_pay_applications_scope_agreement_idx").on(table.tenantId, table.environmentId, table.agreementId),
]);

export const subcontractWaiversTable = pgTable("subcontract_waivers", {
  id: serial("id").primaryKey(),
  payApplicationId: integer("pay_application_id").notNull().references(() => subcontractPayApplicationsTable.id, { onDelete: "cascade" }),
  waiverType: text("waiver_type").notNull(),
  status: text("status").notNull().default("missing"),
  objectPath: text("object_path"),
  receivedAt: timestamp("received_at", { withTimezone: true }),
  reviewedByUserId: integer("reviewed_by_user_id").references(() => usersTable.id, { onDelete: "set null" }),
  reviewedAt: timestamp("reviewed_at", { withTimezone: true }),
  notes: text("notes"),
  tenantId: integer("tenant_id").notNull().references(() => tenantsTable.id, { onDelete: "cascade" }),
  environmentId: integer("environment_id").notNull().references(() => environmentsTable.id, { onDelete: "cascade" }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  uniqueIndex("subcontract_waivers_scope_app_type_idx").on(table.tenantId, table.environmentId, table.payApplicationId, table.waiverType),
  index("subcontract_waivers_scope_status_idx").on(table.tenantId, table.environmentId, table.status),
]);

export const subcontractCloseoutItemsTable = pgTable("subcontract_closeout_items", {
  id: serial("id").primaryKey(),
  agreementId: integer("agreement_id").notNull().references(() => subcontractAgreementsTable.id, { onDelete: "cascade" }),
  itemType: text("item_type").notNull(),
  title: text("title").notNull(),
  status: text("status").notNull().default("open"),
  dueDate: date("due_date", { mode: "string" }),
  objectPath: text("object_path"),
  notes: text("notes"),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  rejectionReason: text("rejection_reason"),
  tenantId: integer("tenant_id").notNull().references(() => tenantsTable.id, { onDelete: "cascade" }),
  environmentId: integer("environment_id").notNull().references(() => environmentsTable.id, { onDelete: "cascade" }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index("subcontract_closeout_scope_agreement_idx").on(table.tenantId, table.environmentId, table.agreementId),
  index("subcontract_closeout_scope_status_idx").on(table.tenantId, table.environmentId, table.status),
]);

export const subcontractAuditEventsTable = pgTable("subcontract_audit_events", {
  id: serial("id").primaryKey(),
  entityType: text("entity_type").notNull(),
  entityId: integer("entity_id").notNull(),
  action: text("action").notNull(),
  fromStatus: text("from_status"),
  toStatus: text("to_status"),
  details: text("details"),
  actorUserId: integer("actor_user_id").references(() => usersTable.id, { onDelete: "set null" }),
  tenantId: integer("tenant_id").notNull().references(() => tenantsTable.id, { onDelete: "cascade" }),
  environmentId: integer("environment_id").notNull().references(() => environmentsTable.id, { onDelete: "cascade" }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index("subcontract_audit_scope_entity_idx").on(table.tenantId, table.environmentId, table.entityType, table.entityId),
]);